### ISSUE TITLE
Deciding upon coding language, coding standard, Testing framework

### ISSUE THREAD

**Issue by priteshgohil** [priteshgohil/AST#5]
Deciding on coding language, coding standard,  and testing framework.

**Comment by jaswanthbjk** [comment]
My choice of the attributes are 
Language chosen : Python
Testing Framework : Unittest
Coding standard : PEP8
@priteshgohil please confirm

**Comment by priteshgohil** [comment]
Yes comparing with our last assignment work, this would be suitable for our project.
