### ISSUE TITLE
Deciding on Structure of code

### ISSUE THREAD

**Issue by jaswanthbjk** [priteshgohil/AST#6]

**Comment by priteshgohil** [comment]
we will implement using class and having different method for given requirement. 
A list of objects with its parameters in tuple will be pass to the class method and implemented method will return the best possible solution. The result then can be used for further given requirement.

Assumptions:
1. the list of tuples containing objects and parameters are passed from the other class/function. 
2. number assigned to particular object are 1.knife 2. scissor 3.fork 4.spoon 5.keys
3. length of two received list assumed to be same
@jaswanthbjk please confirm

**Comment by jaswanthbjk** [comment]
For the given requirements the above guidelines do suffice. Confirming the structure will be followed

**Comment by jaswanthbjk** [comment]
The structure is followed as mentioned. Confirming and closing the issue now
