### ISSUE TITLE
Developing the test cases and implementing the code

### ISSUE THREAD

**Issue by jaswanthbjk** [priteshgohil/AST#7]

**Comment by priteshgohil** [comment]
also we will be looking for refactoring part here.

**Comment by jaswanthbjk** [comment]
The test cases were submitted for peer review

**Comment by priteshgohil** [comment]
updated with the naming convention and written test cases for decided code structure.

**Comment by priteshgohil** [comment]
closing this issue, because test cases and code developed and tested.
